import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { BehaviorSubject, Subject } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class UploadService {
  apiUrl = 'http://localhost:3000';
  fileData: any = new BehaviorSubject({
    msg: 'Success',
    data: [
      {
        id: '000.jpg',
        text: 'CORPORATE',
        left: '188',
        top: '234',
        width: '160',
        height: '27',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'PACKAGING',
        left: '359',
        top: '239',
        width: '151',
        height: '22',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: '&',
        left: '521',
        top: '239',
        width: '16',
        height: '22',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: 'PROMOTIONS',
        left: '548',
        top: '239',
        width: '181',
        height: '22',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Bill',
        left: '690',
        top: '270',
        width: '54',
        height: '28',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'of',
        left: '758',
        top: '271',
        width: '34',
        height: '28',
        conf: '92',
      },
      {
        id: '000.jpg',
        text: 'Lading',
        left: '804',
        top: '271',
        width: '119',
        height: '37',
        conf: '91',
      },
      {
        id: '000.jpg',
        text: 'To',
        left: '421',
        top: '407',
        width: '28',
        height: '16',
        conf: '81',
      },
      {
        id: '000.jpg',
        text: 'Consignee',
        left: '105',
        top: '434',
        width: '122',
        height: '29',
        conf: '82',
      },
      {
        id: '000.jpg',
        text: '—',
        left: '0',
        top: '0',
        width: '1653',
        height: '2339',
        conf: '37',
      },
      {
        id: '000.jpg',
        text: "SAM'S",
        left: '280',
        top: '439',
        width: '77',
        height: '21',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: 'DIST.CTR',
        left: '367',
        top: '440',
        width: '117',
        height: '21',
        conf: '91',
      },
      {
        id: '000.jpg',
        text: '#6493',
        left: '493',
        top: '441',
        width: '71',
        height: '20',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Street',
        left: '106',
        top: '475',
        width: '68',
        height: '22',
        conf: '97',
      },
      {
        id: '000.jpg',
        text: '1000',
        left: '300',
        top: '480',
        width: '53',
        height: '21',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: 'S.',
        left: '363',
        top: '480',
        width: '20',
        height: '21',
        conf: '92',
      },
      {
        id: '000.jpg',
        text: 'CUCAMONGA',
        left: '395',
        top: '480',
        width: '172',
        height: '22',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'AVE',
        left: '575',
        top: '481',
        width: '51',
        height: '22',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: '',
        left: '85',
        top: '423',
        width: '22',
        height: '91',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '708',
        top: '423',
        width: '15',
        height: '91',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'BILL',
        left: '846',
        top: '315',
        width: '64',
        height: '26',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'OF',
        left: '921',
        top: '316',
        width: '42',
        height: '26',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: 'LADING',
        left: '975',
        top: '317',
        width: '118',
        height: '26',
        conf: '92',
      },
      {
        id: '000.jpg',
        text: 'NUMBER:',
        left: '1106',
        top: '319',
        width: '138',
        height: '26',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '8175105',
        left: '1248',
        top: '325',
        width: '118',
        height: '21',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'PO#',
        left: '952',
        top: '355',
        width: '53',
        height: '19',
        conf: '85',
      },
      {
        id: '000.jpg',
        text: 'BILL',
        left: '1043',
        top: '386',
        width: '48',
        height: '19',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'DATE:',
        left: '1100',
        top: '386',
        width: '68',
        height: '20',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'FROM',
        left: '1125',
        top: '416',
        width: '62',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'AR50',
        left: '997',
        top: '448',
        width: '66',
        height: '22',
        conf: '76',
      },
      {
        id: '000.jpg',
        text: 'CORPORATE',
        left: '1081',
        top: '450',
        width: '169',
        height: '23',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'PACKAGING',
        left: '1262',
        top: '452',
        width: '155',
        height: '24',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '820',
        top: '434',
        width: '19',
        height: '56',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'Shipper',
        left: '839',
        top: '445',
        width: '90',
        height: '27',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: '',
        left: '817',
        top: '490',
        width: '14',
        height: '28',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '929',
        top: '434',
        width: '68',
        height: '51',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '1409',
        top: '434',
        width: '102',
        height: '84',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '570',
        top: '514',
        width: '677',
        height: '14',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'Destination',
        left: '107',
        top: '515',
        width: '127',
        height: '24',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: '',
        left: '85',
        top: '514',
        width: '13',
        height: '28',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '708',
        top: '514',
        width: '15',
        height: '37',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '817',
        top: '518',
        width: '15',
        height: '50',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '1476',
        top: '518',
        width: '37',
        height: '50',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '544',
        top: '555',
        width: '943',
        height: '19',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'City/State/Zip',
        left: '107',
        top: '556',
        width: '155',
        height: '29',
        conf: '83',
      },
      {
        id: '000.jpg',
        text: 'ONTARIO,',
        left: '292',
        top: '560',
        width: '122',
        height: '24',
        conf: '83',
      },
      {
        id: '000.jpg',
        text: 'CA',
        left: '425',
        top: '561',
        width: '35',
        height: '21',
        conf: '91',
      },
      {
        id: '000.jpg',
        text: '91761',
        left: '468',
        top: '562',
        width: '68',
        height: '22',
        conf: '91',
      },
      {
        id: '000.jpg',
        text: '',
        left: '89',
        top: '551',
        width: '18',
        height: '48',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '536',
        top: '551',
        width: '187',
        height: '48',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '91',
        top: '599',
        width: '630',
        height: '44',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '0',
        top: '680',
        width: '111',
        height: '93',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '141',
        top: '629',
        width: '537',
        height: '13',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'THIRD',
        left: '272',
        top: '646',
        width: '62',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'PARTY',
        left: '343',
        top: '647',
        width: '67',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'BILLING,',
        left: '419',
        top: '648',
        width: '87',
        height: '21',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'SEND',
        left: '515',
        top: '650',
        width: '56',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'TO',
        left: '578',
        top: '651',
        width: '28',
        height: '17',
        conf: '94',
      },
      {
        id: '000.jpg',
        text: 'Name',
        left: '111',
        top: '679',
        width: '66',
        height: '22',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Arizona',
        left: '373',
        top: '684',
        width: '87',
        height: '22',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Beverages',
        left: '470',
        top: '687',
        width: '123',
        height: '27',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'LLC',
        left: '603',
        top: '689',
        width: '45',
        height: '22',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'C',
        left: '111',
        top: '722',
        width: '16',
        height: '20',
        conf: '44',
      },
      {
        id: '000.jpg',
        text: 'ompany',
        left: '129',
        top: '727',
        width: '90',
        height: '24',
        conf: '49',
      },
      {
        id: '000.jpg',
        text: 'Arizona',
        left: '372',
        top: '728',
        width: '87',
        height: '22',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Beverages',
        left: '470',
        top: '730',
        width: '122',
        height: '29',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'LLC',
        left: '603',
        top: '734',
        width: '45',
        height: '21',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Street',
        left: '112',
        top: '765',
        width: '68',
        height: '23',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'City/State/Zip',
        left: '113',
        top: '808',
        width: '153',
        height: '30',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Street',
        left: '839',
        top: '486',
        width: '69',
        height: '22',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: '1555',
        left: '1040',
        top: '490',
        width: '55',
        height: '22',
        conf: '92',
      },
      {
        id: '000.jpg',
        text: 'S.',
        left: '1105',
        top: '491',
        width: '21',
        height: '21',
        conf: '91',
      },
      {
        id: '000.jpg',
        text: 'ARCHIBALD',
        left: '1138',
        top: '492',
        width: '154',
        height: '23',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'AVENUE',
        left: '1302',
        top: '495',
        width: '107',
        height: '22',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Origin',
        left: '839',
        top: '528',
        width: '68',
        height: '27',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'City/State/Zip',
        left: '840',
        top: '569',
        width: '158',
        height: '30',
        conf: '92',
      },
      {
        id: '000.jpg',
        text: 'ONTARIO,',
        left: '1038',
        top: '573',
        width: '127',
        height: '26',
        conf: '82',
      },
      {
        id: '000.jpg',
        text: 'CA',
        left: '1177',
        top: '576',
        width: '36',
        height: '21',
        conf: '91',
      },
      {
        id: '000.jpg',
        text: '91761',
        left: '1222',
        top: '577',
        width: '71',
        height: '21',
        conf: '91',
      },
      {
        id: '000.jpg',
        text: '',
        left: '1476',
        top: '568',
        width: '38',
        height: '46',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '817',
        top: '568',
        width: '23',
        height: '82',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '1469',
        top: '614',
        width: '45',
        height: '48',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '853',
        top: '602',
        width: '637',
        height: '14',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'Special',
        left: '840',
        top: '610',
        width: '79',
        height: '27',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Instructions:',
        left: '922',
        top: '613',
        width: '154',
        height: '24',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: "SHIPPER'S",
        left: '1013',
        top: '655',
        width: '117',
        height: '27',
        conf: '36',
      },
      {
        id: '000.jpg',
        text: 'INSTRUCTIONS',
        left: '1138',
        top: '658',
        width: '162',
        height: '25',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: '\\',
        left: '1441',
        top: '664',
        width: '2',
        height: '12',
        conf: '83',
      },
      {
        id: '000.jpg',
        text: '',
        left: '818',
        top: '650',
        width: '15',
        height: '12',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '718',
        top: '680',
        width: '819',
        height: '78',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '127',
        top: '758',
        width: '1410',
        height: '15',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '429',
        top: '809',
        width: '841',
        height: '24',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'NO.',
        left: '151',
        top: '861',
        width: '34',
        height: '16',
        conf: '94',
      },
      {
        id: '000.jpg',
        text: 'SHIPPING',
        left: '120',
        top: '884',
        width: '97',
        height: '19',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'CASES',
        left: '134',
        top: '909',
        width: '70',
        height: '19',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'NO.',
        left: '285',
        top: '864',
        width: '35',
        height: '16',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'SHIPPING',
        left: '254',
        top: '888',
        width: '98',
        height: '19',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'PALLETS',
        left: '257',
        top: '913',
        width: '93',
        height: '18',
        conf: '89',
      },
      {
        id: '000.jpg',
        text: 'DESCRIPTION',
        left: '625',
        top: '874',
        width: '141',
        height: '21',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'OF',
        left: '774',
        top: '879',
        width: '28',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'ARTICLES',
        left: '810',
        top: '880',
        width: '103',
        height: '19',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: '!',
        left: '952',
        top: '881',
        width: '2',
        height: '7',
        conf: '48',
      },
      {
        id: '000.jpg',
        text: 'SPECIAL',
        left: '603',
        top: '899',
        width: '89',
        height: '19',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'MARKS',
        left: '700',
        top: '902',
        width: '74',
        height: '18',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: '&',
        left: '783',
        top: '904',
        width: '13',
        height: '17',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: 'EXCEPTIONS:',
        left: '804',
        top: '905',
        width: '133',
        height: '20',
        conf: '62',
      },
      {
        id: '000.jpg',
        text: '',
        left: '552',
        top: '1018',
        width: '505',
        height: '19',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '',
        left: '462',
        top: '1089',
        width: '124',
        height: '62',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'Equip',
        left: '464',
        top: '1162',
        width: '45',
        height: '24',
        conf: '34',
      },
      {
        id: '000.jpg',
        text: '317',
        left: '587',
        top: '1165',
        width: '40',
        height: '22',
        conf: '80',
      },
      {
        id: '000.jpg',
        text: '7',
        left: '747',
        top: '1195',
        width: '6',
        height: '4',
        conf: '38',
      },
      {
        id: '000.jpg',
        text: 'Equip',
        left: '465',
        top: '1200',
        width: '44',
        height: '24',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: 'Arivat:',
        left: '518',
        top: '1202',
        width: '58',
        height: '21',
        conf: '48',
      },
      {
        id: '000.jpg',
        text: '12/20/19',
        left: '588',
        top: '1203',
        width: '99',
        height: '24',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: '0459',
        left: '698',
        top: '1208',
        width: '53',
        height: '23',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Carrier:',
        left: '464',
        top: '1238',
        width: '61',
        height: '20',
        conf: '81',
      },
      {
        id: '000.jpg',
        text: 'BAWB',
        left: '588',
        top: '1241',
        width: '72',
        height: '23',
        conf: '83',
      },
      {
        id: '000.jpg',
        text: '°',
        left: '673',
        top: '1247',
        width: '5',
        height: '5',
        conf: '76',
      },
      {
        id: '000.jpg',
        text: 'Seal:',
        left: '464',
        top: '1276',
        width: '41',
        height: '20',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: '3289785',
        left: '587',
        top: '1279',
        width: '97',
        height: '25',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'REMIT',
        left: '118',
        top: '1146',
        width: '50',
        height: '18',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: 'C.0.D.',
        left: '169',
        top: '1148',
        width: '80',
        height: '18',
        conf: '59',
      },
      {
        id: '000.jpg',
        text: 'ADDRESS:',
        left: '118',
        top: '1276',
        width: '106',
        height: '19',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'Reseal:',
        left: '464',
        top: '1314',
        width: '61',
        height: '22',
        conf: '92',
      },
      {
        id: '000.jpg',
        text: 'Door/Zone:',
        left: '464',
        top: '1353',
        width: '91',
        height: '22',
        conf: '85',
      },
      {
        id: '000.jpg',
        text: 'Del',
        left: '464',
        top: '1392',
        width: '25',
        height: '19',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Date:',
        left: '499',
        top: '1393',
        width: '41',
        height: '21',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'APPOINTMENT',
        left: '588',
        top: '1356',
        width: '180',
        height: '29',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '12/20/19',
        left: '588',
        top: '1395',
        width: '99',
        height: '25',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '0500',
        left: '699',
        top: '1400',
        width: '54',
        height: '23',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: "'",
        left: '463',
        top: '1435',
        width: '3',
        height: '14',
        conf: '55',
      },
      {
        id: '000.jpg',
        text: 'have',
        left: '474',
        top: '1435',
        width: '35',
        height: '16',
        conf: '73',
      },
      {
        id: '000.jpg',
        text: 'read',
        left: '516',
        top: '1438',
        width: '33',
        height: '15',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'and',
        left: '556',
        top: '1440',
        width: '26',
        height: '14',
        conf: '92',
      },
      {
        id: '000.jpg',
        text: 'understan',
        left: '590',
        top: '1441',
        width: '74',
        height: '17',
        conf: '90',
      },
      {
        id: '000.jpg',
        text: 'Appointment',
        left: '464',
        top: '1459',
        width: '94',
        height: '19',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: '/',
        left: '566',
        top: '1463',
        width: '5',
        height: '15',
        conf: '90',
      },
      {
        id: '000.jpg',
        text: 'Drop',
        left: '578',
        top: '1464',
        width: '35',
        height: '19',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Rules',
        left: '621',
        top: '1466',
        width: '42',
        height: '16',
        conf: '84',
      },
      {
        id: '000.jpg',
        text: 'NOTE:',
        left: '120',
        top: '1378',
        width: '60',
        height: '18',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: 'W',
        left: '187',
        top: '1381',
        width: '20',
        height: '16',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: 'here',
        left: '214',
        top: '1382',
        width: '29',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'the',
        left: '244',
        top: '1384',
        width: '32',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'rate',
        left: '278',
        top: '1386',
        width: '53',
        height: '16',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'is',
        left: '339',
        top: '1386',
        width: '12',
        height: '16',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: 'depende',
        left: '359',
        top: '1387',
        width: '81',
        height: '21',
        conf: '90',
      },
      {
        id: '000.jpg',
        text: 'on',
        left: '119',
        top: '1407',
        width: '10',
        height: '12',
        conf: '92',
      },
      {
        id: '000.jpg',
        text: 'value,',
        left: '131',
        top: '1405',
        width: '70',
        height: '19',
        conf: '92',
      },
      {
        id: '000.jpg',
        text: 'shippers',
        left: '209',
        top: '1407',
        width: '78',
        height: '21',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'are',
        left: '294',
        top: '1414',
        width: '29',
        height: '13',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'required',
        left: '331',
        top: '1413',
        width: '74',
        height: '19',
        conf: '44',
      },
      {
        id: '000.jpg',
        text: 'to',
        left: '413',
        top: '1415',
        width: '16',
        height: '16',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'State',
        left: '119',
        top: '1429',
        width: '43',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'specifically',
        left: '170',
        top: '1432',
        width: '99',
        height: '22',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: 'in',
        left: '277',
        top: '1434',
        width: '14',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'writing',
        left: '298',
        top: '1437',
        width: '59',
        height: '21',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'the',
        left: '365',
        top: '1438',
        width: '28',
        height: '17',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: 'agre',
        left: '401',
        top: '1443',
        width: '39',
        height: '17',
        conf: '92',
      },
      {
        id: '000.jpg',
        text: 'or',
        left: '120',
        top: '1457',
        width: '17',
        height: '12',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'declared',
        left: '143',
        top: '1454',
        width: '78',
        height: '19',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'value',
        left: '228',
        top: '1458',
        width: '49',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'of',
        left: '285',
        top: '1460',
        width: '17',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'the',
        left: '308',
        top: '1461',
        width: '27',
        height: '17',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'Property.',
        left: '343',
        top: '1465',
        width: '76',
        height: '20',
        conf: '90',
      },
      {
        id: '000.jpg',
        text: '7',
        left: '431',
        top: '1465',
        width: '9',
        height: '17',
        conf: '88',
      },
      {
        id: '000.jpg',
        text: 'agreed',
        left: '120',
        top: '1481',
        width: '62',
        height: '18',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'or',
        left: '189',
        top: '1485',
        width: '18',
        height: '13',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'declared',
        left: '213',
        top: '1483',
        width: '79',
        height: '18',
        conf: '94',
      },
      {
        id: '000.jpg',
        text: 'value',
        left: '300',
        top: '1487',
        width: '48',
        height: '17',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'of',
        left: '356',
        top: '1488',
        width: '18',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'the',
        left: '379',
        top: '1489',
        width: '28',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Driver',
        left: '462',
        top: '1502',
        width: '47',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Signature:',
        left: '516',
        top: '1504',
        width: '78',
        height: '20',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: 'Property',
        left: '120',
        top: '1507',
        width: '74',
        height: '19',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'is',
        left: '202',
        top: '1507',
        width: '13',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'hereby',
        left: '223',
        top: '1508',
        width: '62',
        height: '22',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'specifically',
        left: '292',
        top: '1512',
        width: '100',
        height: '23',
        conf: '92',
      },
      {
        id: '000.jpg',
        text: 'state',
        left: '399',
        top: '1516',
        width: '40',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'by',
        left: '120',
        top: '1528',
        width: '10',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'the',
        left: '131',
        top: '1530',
        width: '43',
        height: '19',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'shipper',
        left: '182',
        top: '1532',
        width: '60',
        height: '21',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: 'to',
        left: '244',
        top: '1535',
        width: '28',
        height: '16',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: 'be',
        left: '280',
        top: '1535',
        width: '21',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'not',
        left: '309',
        top: '1538',
        width: '27',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'exceeding',
        left: '343',
        top: '1541',
        width: '94',
        height: '21',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: '|',
        left: '461',
        top: '1536',
        width: '6',
        height: '58',
        conf: '87',
      },
      {
        id: '000.jpg',
        text: '||',
        left: '478',
        top: '1537',
        width: '18',
        height: '59',
        conf: '87',
      },
      {
        id: '000.jpg',
        text: '|',
        left: '564',
        top: '1540',
        width: '6',
        height: '60',
        conf: '91',
      },
      {
        id: '000.jpg',
        text: '|',
        left: '644',
        top: '1545',
        width: '11',
        height: '59',
        conf: '78',
      },
      {
        id: '000.jpg',
        text: '|',
        left: '664',
        top: '1546',
        width: '23',
        height: '60',
        conf: '66',
      },
      {
        id: '000.jpg',
        text: '$',
        left: '121',
        top: '1553',
        width: '9',
        height: '17',
        conf: '88',
      },
      {
        id: '000.jpg',
        text: 'fic.',
        left: '416',
        top: '1594',
        width: '23',
        height: '18',
        conf: '88',
      },
      {
        id: '000.jpg',
        text: 'per',
        left: '342',
        top: '1568',
        width: '27',
        height: '13',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'RECEIVED',
        left: '121',
        top: '1581',
        width: '104',
        height: '20',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Subject',
        left: '232',
        top: '1587',
        width: '60',
        height: '21',
        conf: '83',
      },
      {
        id: '000.jpg',
        text: 'to',
        left: '292',
        top: '1590',
        width: '29',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'the',
        left: '328',
        top: '1591',
        width: '28',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'classi',
        left: '363',
        top: '1592',
        width: '51',
        height: '18',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'good',
        left: '120',
        top: '1608',
        width: '44',
        height: '19',
        conf: '90',
      },
      {
        id: '000.jpg',
        text: 'order,',
        left: '172',
        top: '1609',
        width: '52',
        height: '20',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'except',
        left: '233',
        top: '1615',
        width: '60',
        height: '18',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'as',
        left: '301',
        top: '1618',
        width: '20',
        height: '14',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'noted',
        left: '329',
        top: '1617',
        width: '50',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: '(conte',
        left: '387',
        top: '1618',
        width: '52',
        height: '20',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'Delivery;',
        left: '461',
        top: '1619',
        width: '68',
        height: '21',
        conf: '84',
      },
      {
        id: '000.jpg',
        text: '94060718',
        left: '557',
        top: '1617',
        width: '113',
        height: '27',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '(the',
        left: '120',
        top: '1632',
        width: '34',
        height: '19',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'word',
        left: '162',
        top: '1635',
        width: '44',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'carrier',
        left: '215',
        top: '1639',
        width: '59',
        height: '15',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'being',
        left: '282',
        top: '1639',
        width: '49',
        height: '22',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: 'understooc',
        left: '341',
        top: '1643',
        width: '98',
        height: '19',
        conf: '35',
      },
      {
        id: '000.jpg',
        text: 'agrees',
        left: '120',
        top: '1660',
        width: '62',
        height: '18',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'to',
        left: '193',
        top: '1661',
        width: '16',
        height: '16',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: 'carry',
        left: '220',
        top: '1665',
        width: '45',
        height: '19',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: 'to',
        left: '275',
        top: '1665',
        width: '17',
        height: '16',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'its',
        left: '303',
        top: '1665',
        width: '19',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'usual',
        left: '334',
        top: '1669',
        width: '47',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'place',
        left: '393',
        top: '1670',
        width: '46',
        height: '20',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'destination.',
        left: '119',
        top: '1681',
        width: '100',
        height: '21',
        conf: '92',
      },
      {
        id: '000.jpg',
        text: 'It',
        left: '222',
        top: '1687',
        width: '22',
        height: '17',
        conf: '91',
      },
      {
        id: '000.jpg',
        text: 'is',
        left: '253',
        top: '1692',
        width: '12',
        height: '13',
        conf: '87',
      },
      {
        id: '000.jpg',
        text: 'mutually',
        left: '273',
        top: '1691',
        width: '77',
        height: '22',
        conf: '91',
      },
      {
        id: '000.jpg',
        text: 'agreed',
        left: '358',
        top: '1696',
        width: '63',
        height: '19',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: '¢',
        left: '430',
        top: '1701',
        width: '8',
        height: '12',
        conf: '76',
      },
      {
        id: '000.jpg',
        text: 'Party',
        left: '119',
        top: '1709',
        width: '46',
        height: '20',
        conf: '94',
      },
      {
        id: '000.jpg',
        text: 'at',
        left: '173',
        top: '1711',
        width: '16',
        height: '15',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'any',
        left: '197',
        top: '1715',
        width: '32',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'time',
        left: '237',
        top: '1713',
        width: '38',
        height: '18',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'interested',
        left: '284',
        top: '1715',
        width: '78',
        height: '20',
        conf: '94',
      },
      {
        id: '000.jpg',
        text: 'in',
        left: '363',
        top: '1720',
        width: '33',
        height: '16',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'all',
        left: '406',
        top: '1722',
        width: '19',
        height: '16',
        conf: '93',
      },
      {
        id: '000.jpg',
        text: '¢',
        left: '433',
        top: '1726',
        width: '5',
        height: '13',
        conf: '83',
      },
      {
        id: '000.jpg',
        text: 'and',
        left: '119',
        top: '1734',
        width: '33',
        height: '16',
        conf: '86',
      },
      {
        id: '000.jpg',
        text: 'conditions',
        left: '161',
        top: '1736',
        width: '83',
        height: '18',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'in',
        left: '246',
        top: '1739',
        width: '32',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'the',
        left: '286',
        top: '1741',
        width: '28',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'governing',
        left: '323',
        top: '1746',
        width: '91',
        height: '22',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'cl',
        left: '422',
        top: '1748',
        width: '15',
        height: '17',
        conf: '94',
      },
      {
        id: '000.jpg',
        text: 'and',
        left: '119',
        top: '1759',
        width: '33',
        height: '16',
        conf: '94',
      },
      {
        id: '000.jpg',
        text: 'conditions',
        left: '160',
        top: '1761',
        width: '83',
        height: '18',
        conf: '94',
      },
      {
        id: '000.jpg',
        text: 'in',
        left: '245',
        top: '1764',
        width: '30',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'the',
        left: '282',
        top: '1766',
        width: '29',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'and',
        left: '670',
        top: '1469',
        width: '26',
        height: '15',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Regulations',
        left: '703',
        top: '1470',
        width: '89',
        height: '19',
        conf: '90',
      },
      {
        id: '000.jpg',
        text: 'id',
        left: '666',
        top: '1444',
        width: '8',
        height: '15',
        conf: '69',
      },
      {
        id: '000.jpg',
        text: 'the',
        left: '681',
        top: '1444',
        width: '23',
        height: '16',
        conf: '94',
      },
      {
        id: '000.jpg',
        text: 'posted',
        left: '711',
        top: '1448',
        width: '51',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Copy',
        left: '770',
        top: '1453',
        width: '33',
        height: '15',
        conf: '80',
      },
      {
        id: '000.jpg',
        text: 'of',
        left: '812',
        top: '1452',
        width: '12',
        height: '14',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: "Wal-Mart's:",
        left: '833',
        top: '1453',
        width: '98',
        height: '19',
        conf: '54',
      },
      {
        id: '000.jpg',
        text: 'LY',
        left: '937',
        top: '1441',
        width: '104',
        height: '75',
        conf: '75',
      },
      {
        id: '000.jpg',
        text: '',
        left: '0',
        top: '773',
        width: '1537',
        height: '1501',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'Status:',
        left: '822',
        top: '1178',
        width: '55',
        height: '20',
        conf: '68',
      },
      {
        id: '000.jpg',
        text: 'Tempt:',
        left: '823',
        top: '1216',
        width: '61',
        height: '25',
        conf: '88',
      },
      {
        id: '000.jpg',
        text: 'Temp2:',
        left: '823',
        top: '1254',
        width: '61',
        height: '25',
        conf: '88',
      },
      {
        id: '000.jpg',
        text: 'PREPAID',
        left: '1333',
        top: '1215',
        width: '94',
        height: '19',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'COLLECT',
        left: '1333',
        top: '1242',
        width: '101',
        height: '20',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'Temp3:',
        left: '823',
        top: '1293',
        width: '62',
        height: '25',
        conf: '89',
      },
      {
        id: '000.jpg',
        text: 'Fuel',
        left: '823',
        top: '1331',
        width: '35',
        height: '20',
        conf: '92',
      },
      {
        id: '000.jpg',
        text: 'Lvl:7',
        left: '867',
        top: '1333',
        width: '29',
        height: '20',
        conf: '48',
      },
      {
        id: '000.jpg',
        text: '25',
        left: '918',
        top: '1333',
        width: '27',
        height: '22',
        conf: '48',
      },
      {
        id: '000.jpg',
        text: 'Dept:',
        left: '824',
        top: '1370',
        width: '42',
        height: '24',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'SPLT',
        left: '920',
        top: '1372',
        width: '60',
        height: '34',
        conf: '91',
      },
      {
        id: '000.jpg',
        text: 'Type:',
        left: '824',
        top: '1409',
        width: '44',
        height: '24',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: '537',
        left: '919',
        top: '1411',
        width: '40',
        height: '27',
        conf: '52',
      },
      {
        id: '000.jpg',
        text: 'CHARGES',
        left: '1333',
        top: '1296',
        width: '93',
        height: '19',
        conf: '92',
      },
      {
        id: '000.jpg',
        text: '$',
        left: '1428',
        top: '1299',
        width: '33',
        height: '19',
        conf: '88',
      },
      {
        id: '000.jpg',
        text: 'Freight',
        left: '1337',
        top: '1427',
        width: '64',
        height: '22',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Charges',
        left: '1409',
        top: '1430',
        width: '84',
        height: '23',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'are',
        left: '1337',
        top: '1457',
        width: '28',
        height: '13',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'collect',
        left: '1373',
        top: '1456',
        width: '62',
        height: '18',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'unless',
        left: '1338',
        top: '1480',
        width: '59',
        height: '18',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'market',
        left: '1405',
        top: '1483',
        width: '68',
        height: '18',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'prepaid',
        left: '1338',
        top: '1509',
        width: '68',
        height: '16',
        conf: '80',
      },
      {
        id: '000.jpg',
        text: 'CHECK',
        left: '1339',
        top: '1556',
        width: '75',
        height: '20',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'BOX',
        left: '1422',
        top: '1560',
        width: '31',
        height: '17',
        conf: '94',
      },
      {
        id: '000.jpg',
        text: 'IF',
        left: '1456',
        top: '1561',
        width: '39',
        height: '18',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'PREPAID',
        left: '1341',
        top: '1583',
        width: '92',
        height: '20',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: '',
        left: '1313',
        top: '976',
        width: '14',
        height: '651',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: "'",
        left: '1222',
        top: '1636',
        width: '4',
        height: '8',
        conf: '34',
      },
      {
        id: '000.jpg',
        text: 'described',
        left: '1234',
        top: '1633',
        width: '91',
        height: '19',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'above',
        left: '1334',
        top: '1637',
        width: '42',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'in',
        left: '1378',
        top: '1642',
        width: '33',
        height: '12',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'apparent',
        left: '1420',
        top: '1643',
        width: '87',
        height: '17',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: '‘ated',
        left: '1222',
        top: '1659',
        width: '44',
        height: '16',
        conf: '59',
      },
      {
        id: '000.jpg',
        text: 'above',
        left: '1274',
        top: '1660',
        width: '57',
        height: '18',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'which',
        left: '1338',
        top: '1664',
        width: '51',
        height: '15',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'said',
        left: '1398',
        top: '1666',
        width: '38',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'carrier',
        left: '1445',
        top: '1670',
        width: '62',
        height: '15',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: '2',
        left: '1222',
        top: '1687',
        width: '6',
        height: '12',
        conf: '78',
      },
      {
        id: '000.jpg',
        text: 'property',
        left: '1237',
        top: '1688',
        width: '78',
        height: '19',
        conf: '72',
      },
      {
        id: '000.jpg',
        text: 'under',
        left: '1324',
        top: '1689',
        width: '51',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'the',
        left: '1383',
        top: '1690',
        width: '28',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'contract)',
        left: '1422',
        top: '1694',
        width: '85',
        height: '20',
        conf: '81',
      },
      {
        id: '000.jpg',
        text: 'Carrier',
        left: '1238',
        top: '1714',
        width: '60',
        height: '14',
        conf: '90',
      },
      {
        id: '000.jpg',
        text: 'on',
        left: '1309',
        top: '1717',
        width: '22',
        height: '12',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'the',
        left: '1342',
        top: '1715',
        width: '27',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'route',
        left: '1381',
        top: '1718',
        width: '46',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'to',
        left: '1440',
        top: '1720',
        width: '17',
        height: '15',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'said',
        left: '1469',
        top: '1721',
        width: '38',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'to',
        left: '1229',
        top: '1736',
        width: '17',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'destination',
        left: '1254',
        top: '1736',
        width: '101',
        height: '20',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'and',
        left: '1364',
        top: '1742',
        width: '32',
        height: '16',
        conf: '94',
      },
      {
        id: '000.jpg',
        text: 'as',
        left: '1405',
        top: '1746',
        width: '22',
        height: '13',
        conf: '94',
      },
      {
        id: '000.jpg',
        text: 'to',
        left: '1435',
        top: '1745',
        width: '18',
        height: '15',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'each',
        left: '1462',
        top: '1746',
        width: '45',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'tto',
        left: '1223',
        top: '1762',
        width: '28',
        height: '16',
        conf: '74',
      },
      {
        id: '000.jpg',
        text: 'all',
        left: '1259',
        top: '1763',
        width: '20',
        height: '16',
        conf: '94',
      },
      {
        id: '000.jpg',
        text: 'the',
        left: '1287',
        top: '1764',
        width: '28',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Bill',
        left: '1324',
        top: '1764',
        width: '26',
        height: '18',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'of',
        left: '1358',
        top: '1766',
        width: '17',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Lading',
        left: '1382',
        top: '1767',
        width: '63',
        height: '23',
        conf: '91',
      },
      {
        id: '000.jpg',
        text: 'terms',
        left: '1454',
        top: '1771',
        width: '54',
        height: '18',
        conf: '95',
      },
      {
        id: '000.jpg',
        text: 'ith',
        left: '1226',
        top: '1787',
        width: '21',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'all',
        left: '1257',
        top: '1789',
        width: '19',
        height: '15',
        conf: '90',
      },
      {
        id: '000.jpg',
        text: 'the',
        left: '1285',
        top: '1789',
        width: '28',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Bill',
        left: '1323',
        top: '1790',
        width: '25',
        height: '17',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'of',
        left: '1357',
        top: '1792',
        width: '16',
        height: '16',
        conf: '96',
      },
      {
        id: '000.jpg',
        text: 'Lading',
        left: '1381',
        top: '1793',
        width: '63',
        height: '23',
        conf: '92',
      },
      {
        id: '000.jpg',
        text: 'terms',
        left: '1454',
        top: '1797',
        width: '54',
        height: '17',
        conf: '96',
      },
    ],
    invoicePath: 'uploads\\invoice.jpg',
  });

  constructor(private http: HttpClient, private route: Router) {}
  upload(formData: any) {
    this.http.post(`${this.apiUrl}/upload`, formData).subscribe((data) => {
      console.log(data);
      this.fileData.next(data);
      this.route.navigate(['/invoice-detail']);
    });
  }

  saveCsv(updatedObj: any) {
    this.http
      .post(`${this.apiUrl}/save`, { data: updatedObj })
      .subscribe((data) => {
        console.log(data);
      });
  }
}
